{{ if .Values.fargate.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-data
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
   capacity:
      storage: {{ .Values.fargate.efs.hyperglance.storageCapacity }}
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: {{ .Values.fargate.storageClassName }}
   claimRef:
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-data
   csi:
      driver: efs.csi.aws.com
      volumeHandle: {{ printf "%s:%s:%s" $.Values.fargate.efs.filesystem_id $.Values.fargate.efs.hyperglance.sub_path $.Values.fargate.efs.hyperglance.accesspoint_id | quote }}

{{ if not .Values.customPostgres.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgresql-data
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
   capacity:
      storage: {{ .Values.fargate.efs.postgresql.storageCapacity }}
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: {{ .Values.fargate.storageClassName }}
   claimRef:
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-postgresql-data
   csi:
      driver: efs.csi.aws.com
      volumeHandle: {{ printf "%s:%s:%s" $.Values.fargate.efs.filesystem_id $.Values.fargate.efs.postgresql.sub_path $.Values.fargate.efs.postgresql.accesspoint_id | quote }}
{{ end }}
{{ end }}