apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-data"
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
{{ if .Values.eks.enabled }}
  storageClassName: efs-sc
{{ end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

{{ if not .Values.customPostgres.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-postgresql-data"
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
{{ if .Values.eks.enabled }}
  storageClassName: efs-sc
{{ end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
{{ end }}

