apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-data"
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.pvc.annotations }}
  annotations:
    {{- .Values.pvc.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
{{ if .Values.fargate.enabled }}
  storageClassName: {{ .Values.fargate.storageClassName }}
{{ end }}
{{ if and (not .Values.fargate.enabled) ( .Values.pvc.storageClassName) }}
  storageClassName: {{ .Values.pvc.storageClassName }}
{{ end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest.hyperglance }}

{{ if not .Values.customPostgres.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-postgresql-data"
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.pvc.annotations }}
  annotations:
    {{- .Values.pvc.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
{{ if and (not .Values.fargate.enabled) ( .Values.pvc.storageClassName) }}
  storageClassName: {{ .Values.pvc.storageClassName }}
{{ end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest.postgres }}
{{ end }}

