{{ if not .Values.httpdSSL.existingSecretName  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-httpd-ssl"
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  hyperglance.crt: {{- .Values.httpdSSL.certificate | toYaml | indent 1 }}
  hyperglance.key: {{- .Values.httpdSSL.key | toYaml | indent 1 }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-license"
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  hg.bin: {{ .Values.hgBin }}

{{ if and (.Values.saml.enabled) (not .Values.saml.existingSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-httpd-saml"
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  idp.xml: {{- .Values.saml.idpXml | toYaml | indent 1 }}
  sp.xml: {{- .Values.saml.spXml | toYaml | indent 1 }}
  sp.cert: {{- .Values.saml.spCert | toYaml | indent 1 }}
  sp.key: {{- .Values.saml.spKey | toYaml | indent 1 }}
{{ end }}

{{ if and (.Values.customPostgres.enabled) (not .Values.customPostgres.existingSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-custom-postgresql-db"
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  POSTGRESQL_HOST: "{{ .Values.customPostgres.host }}"
  POSTGRESQL_PORT: "{{ .Values.customPostgres.port }}"
  POSTGRESQL_USERNAME: "{{ .Values.customPostgres.user }}"
  POSTGRESQL_PASSWORD: "{{ .Values.customPostgres.pass }}"
{{ end }}

{{ if and (.Values.proxy.enabled) (not .Values.proxy.existingSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-proxy-settings"
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  PROXY_HOST: "{{ .Values.proxy.host }}"
  PROXY_PORT: "{{ .Values.proxy.port }}"
  PROXY_USER: "{{ .Values.proxy.user }}"
  PROXY_PASSWORD: "{{ .Values.proxy.pass }}"
{{ end }}

{{ if and (.Values.privateImageRepo.enabled) (not .Values.privateImageRepo.existingSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-repo-secret
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  .dockerconfigjson: "{{ template "imagePullSecret" . }}"
type: kubernetes.io/dockerconfigjson
{{ end }}