{{ if .Values.serviceAccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  {{- if .Values.serviceAccount.iamRole }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.iamRole }}
  {{- end }}
{{ end }}